[build]
  command = "npm run build"
  publish = "dist"

# 301 Redirect from old domain to new domain
[[redirects]]
  from = "https://pile-ou-face.org/*"
  to = "https://pile-ouface.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.pile-ou-face.org/*"
  to = "https://pile-ouface.fr/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
